version: '3.7'
services:
        todoapp:
                image: todoapp
                build: ./ToDoListApp
                ports:
                   - target: 8585
        react:
                image: react
                build: ./reacttodolist/todolist
                ports:
                   - target: 3000
                depends_on:
                         -  mysql
        mysql:
              image: mysql:5.7
              environment:
                      - MYSQL_ROOT_PASSWORD=password
                      - MYSQL_DATABASE=todolistdb
              volumes:
                      - type: volume
                        source: mysqldata
                        target: /var/lib/mysql

        nginx:
              image: nginx-proj:latest
              build: ./nginx/
              depends_on:
                      - todoapp
                      - react
              ports:
                 - target: 80
                   published: 80
volumes:
        mysqldata:        
